name: Terrains App main CD
on:
  push:
    branches:
      - main
      - chore/setup-ios-deployment
jobs:
  Build-and-Deploy:
    runs-on: macos-latest
    steps:
      - name: Build and deploy with fastlane
        uses: maierj/fastlane-action@v1.4.0
        with: 
          lane: deploy
          subdirectory: 'ios'
